language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
env:
	global:
  	- DB_PASS=Event.4ever!
		- DB_HOST=interopeventstestserver.database.windows.net
		- DB_USER=EventAdmin@interopeventstestserver
		- DB_NAME=InteropEventsDBTest
  	- TIMEOUT=1000
before_install:
  - npm install -g grunt-cli
script: grunt test
