language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
env:
    global:
        - secure: "j8zZidrlbPOdXPx53KJwvhy3TikbRxs6NZQcR2ADsg/I0mzWP43gTpZE8lUWbGO6Kux09sknFohh49Gx8u1wavFBQ4mw/mqtQrzcQetXMMyDxpljbY8gIwOQ98p623HbDfHyT0un8V2duLpE8Hc1sW2TON4IsepizFZRyrAc+UGyOB2J+mMOS+IUoieGPLzAFB97Ii09B8F4bDOsbwmPp1QPGRtjmVV4t86TeHZx1hLlBMUl3/ebIpnaKp0Njr+VGeNmbbbvGtl9CWZeqTgoOL+pp0jA0Uyif+VL4A7NMX39TsTUcMPfSqq+fzRgoh5nrwiZnW4b1OqBeLUVAW5WUqggBumXemg7MXihnLl7bldxQZcWyPylAb4gCQk2Y2y84FD3qAT/RxSSbCus/U8ctFeSI1ApVVI3D6uS4Y8NOoFEywhW96rkAcYgtjzSN/vLZVR3R5GWcEqFTHFb4iFCbAhtqsxCCBWYg6m7/UsqD+6uCS79lxOJnfdYMTIqzN+xU4QUmnldwvnhGr6KbVczCPJuGcfy5///H454B145KS7eYaYm22q+IYS9XRIemDKt305WMykXLdQAmvPBa8vt2qb6/vDE+FmxfYmchlvaBJZD8QNLNZk2YJ6cJ61mY17bincpbK4o4Hf8bMupEfDaOe7fsIgpuzCiDQo0I8HvzfA="
before_install:
  - npm install -g grunt-cli
script: grunt test
